import type { TokenUsage } from "@intx/types/runtime";

import { lookupModelPricing, type ModelPricing, type PricingCache } from "./pricing-fetcher.js";
import { contextTokensFromUsage } from "../provider/context-window.js";

export interface FaremeterConfig {
  inputPricePerToken: number;
  outputPricePerToken: number;
  cacheReadPricePerToken: number;
}

export type CreateFaremeterConfig = Partial<FaremeterConfig> & {
  modelId?: string;
  pricingCache?: PricingCache | null;
  // Resolves the active model's pricing at the moment usage is recorded, so a
  // mid-session model switch prices each turn correctly. Consulted per
  // addUsage; a null result falls back to the static config below.
  resolvePricing?: () => ModelPricing | null;
};

export interface Faremeter {
  addUsage(usage: TokenUsage): void;
  getTotalCost(): number;
  getTotalTokens(): number;
  // Context window size of the most recent turn (input + cacheRead + cacheWrite).
  // Reflects what is actually in context right now, not a cumulative sum.
  getInputTokens(): number;
  // Cumulative tokens generated by the model (output + thinking) across all turns.
  getOutputTokens(): number;
}

// Fallback rate for a model with no known pricing (absent from the models.dev
// cache and no explicit override). A rough estimate so the figure is non-zero
// rather than misleadingly free; real rates come from the resolver.
const DEFAULT_CONFIG: FaremeterConfig = {
  inputPricePerToken: 0.000002,
  outputPricePerToken: 0.00001,
  cacheReadPricePerToken: 0,
};

export function createFaremeter(config: CreateFaremeterConfig = {}): Faremeter {
  const staticPricing =
    config.modelId === undefined
      ? null
      : lookupModelPricing(config.pricingCache ?? null, config.modelId);
  const explicitConfig = { ...config };
  delete explicitConfig.modelId;
  delete explicitConfig.pricingCache;
  delete explicitConfig.resolvePricing;
  const { resolvePricing } = config;

  // Explicit per-token overrides always win; otherwise the live resolver (if
  // any) takes precedence over the static model pricing, then the default.
  const pricesFor = (): FaremeterConfig => ({
    ...DEFAULT_CONFIG,
    ...(resolvePricing?.() ?? staticPricing),
    ...explicitConfig,
  });

  let lastContextSize = 0;
  let outputTokens = 0;
  let totalCost = 0;

  return {
    addUsage(usage: TokenUsage): void {
      const { inputPricePerToken, outputPricePerToken, cacheReadPricePerToken } = pricesFor();
      lastContextSize = contextTokensFromUsage(usage);
      outputTokens += usage.output + usage.thinking;
      totalCost +=
        usage.input * inputPricePerToken +
        usage.output * outputPricePerToken +
        usage.cacheRead * cacheReadPricePerToken;
    },
    getTotalCost(): number {
      return totalCost;
    },
    getTotalTokens(): number {
      return lastContextSize + outputTokens;
    },
    getInputTokens(): number {
      return lastContextSize;
    },
    getOutputTokens(): number {
      return outputTokens;
    },
  };
}

export function formatCost(cost: number): string {
  return `$${cost.toFixed(4)}`;
}
