export {
  AGENTS_PANEL_MAX_VISIBLE,
  COLLAPSE_ORDER,
  FLEET_BOARD_CAP_FRACTION,
  FLEET_FLOOR_MIN_LANES,
  FLEET_TRANSCRIPT_FLOOR,
  IDLE_TRANSCRIPT_FLOOR,
  OVERLAY_MAX_FRACTION,
  OVERLAY_MIN_ROWS,
  OVERLAY_TRANSCRIPT_FLOOR,
  PAINT_ORDER,
  PROMPT_BASE_ROWS,
  PROMPT_BORDER_ROWS,
  PROMPT_CAP_FRACTION,
  PROMPT_IDLE_INPUT_ROWS,
  PROMPT_IDLE_ROWS,
  TASKS_PANEL_MAX_VISIBLE,
  ZONE_IDS,
  ZONE_REGISTRY,
  zoneDeclaration,
  type ZoneDeclaration,
  type ZoneId,
} from "./zones.js";

export {
  BOTTOM_MARGIN_MIN_ROWS,
  BOTTOM_MARGIN_ROWS,
  MARGIN_MIN_COLUMNS,
  SIDE_MARGIN,
  TOP_PAD_MIN_TRANSCRIPT_ROWS,
  TOP_PAD_ROWS,
  resolveBottomMarginRows,
  resolveContentWidth,
  resolveSideMargin,
  resolveTopPadRows,
} from "./margins.js";

export {
  desiredHeights,
  resolveGeometry,
  type GeometryInput,
  type GeometryLayout,
  type OverlayInput,
  type OverlayMode,
  type Rect,
  type TerminalSize,
  type ZoneVisibility,
} from "./resolve.js";
